apiVersion: v1
kind: Service
metadata:
  name: resume-builder
  namespace: resume-builder
  labels:
    app: resume-builder
spec:
  type: ClusterIP
  selector:
    app: resume-builder
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP