apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hemang360/gitops-homelab.git
    targetRevision: main
    path: apps/simg
  destination:
    server: https://kubernetes.default.svc
    namespace: simg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true