apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: simg
 namespace: simg
 annotations:
 cert-manager.io/cluster-issuer: selfsigned
spec:
 ingressClassName: nginx
 tls:
 - hosts: ["simg.homelab.local"]
 secretName: simg-tls
 rules:
 - host: simg.homelab.local
 http:
 paths:
 - path: /
 pathType: Prefix
 backend:
 service:
 name: simg
 port:
 number: 80